In [16]:
import numpy as np

In [5]:
random_array1 = np.random.randint(0,10, size = (5,3))
random_array1

array([[9, 9, 9],
       [6, 5, 1],
       [3, 2, 3],
       [5, 6, 2],
       [9, 9, 7]])

In [16]:
# Sudo random number
np.random.seed(0)
random_array2 = np.random.randint(0,10, size = (5,3))
random_array2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [22]:
random_array3 = np.random.random((5,3))
random_array3

array([[0.57019677, 0.43860151, 0.98837384],
       [0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514],
       [0.65632959, 0.13818295, 0.19658236]])

In [28]:
np.random.seed(0)
random_array3 = np.random.random((5,3))
random_array3

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## 3. Viewing Array and Metric

In [31]:
np.unique(random_array3)

array([0.0202184 , 0.0871293 , 0.11827443, 0.14335329, 0.41466194,
       0.46147936, 0.52184832, 0.63992102, 0.77815675, 0.78052918,
       0.79915856, 0.83261985, 0.87001215, 0.94466892, 0.97861834])

In [3]:
# Demo of std and var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array ([2,4,6,8,10])

In [4]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [5]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [6]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)

In [7]:
data = [1,2,3,4,5,6]
np.mean(data)

3.5

## Dot product example (nut butter sales)

In [14]:
np.random.seed(0)
# Number of jars sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

## Create weekly sales data Frame

In [10]:
import pandas as pd

In [15]:
weekly_sales = pd.DataFrame(sales_amount,index=(["Mon", "TUE","WED", "THU","FRI"]),columns=(["Almod butter","Peanut butter","Cashew butter"]))
weekly_sales

Almod butter  Peanut butter  Cashew butter
Mon            12             15              0
TUE             3              3              7
WED             9             19             18
THU             4              6             12
FRI             1              6              7

In [35]:
# Create price array

price = np.array(["10","8","12"])
price

array(['10', '8', '12'], dtype='<U2')

In [24]:
price.shape

(3,)

In [27]:
price.reshape(1,3)

array([['10', '8', '12']], dtype='<U2')

In [41]:
butter_price = pd.DataFrame(price.reshape(1,3),index=(["Price"]), columns=(["Almod butter","Peanut butter","Cashew butter"]))
butter_price

Almod butter Peanut butter Cashew butter
Price           10             8            12

In [31]:
sales_amount.shape

(5, 3)

In [32]:
price.shape

(3,)

In [39]:
total_sales = price.astype(int).dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [49]:
butter_price.shape, weekly_sales.shape
weekly_sales

Almod butter  Peanut butter  Cashew butter  Total($)
Mon            12             15              0       240
TUE             3              3              7       138
WED             9             19             18       458
THU             4              6             12       232
FRI             1              6              7       142

In [46]:
# weekly_sales["Total($)"] = total_sales 
# weekly_sales

Almod butter  Peanut butter  Cashew butter  Total($)
Mon            12             15              0       240
TUE             3              3              7       138
WED             9             19             18       458
THU             4              6             12       232
FRI             1              6              7       142